// <auto-generated />
using System;
using MVCwithAuth.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCwithAuth.Migrations.MVCwithAuth
{
    [DbContext(typeof(MVCwithAuthContext))]
    [Migration("20190813202201_updateControllerAndViews")]
    partial class updateControllerAndViews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("MVCwithAuth.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("City");

                    b.Property<string>("Content");

                    b.Property<string>("Publisher");

                    b.Property<string>("Tags");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("Title");

                    b.Property<string>("Year");

                    b.Property<string>("userEmail");

                    b.HasKey("Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("MVCwithAuth.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
